/*
 * Source code generated by uk.ac.leeds.ccg.data.fire.process.F_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.projects.fire.data.dwellings;

import uk.ac.leeds.ccg.projects.fire.id.F_RecordID;

public class F_Dwellings_Record2 extends F_Dwellings_Record0 {

    private static final long serialVersionUID = 1L;
             
    protected String tFSO_APPLY;
    protected String tSAFETY_SYSTEM;

    public F_Dwellings_Record2(F_RecordID i, String[] s) throws Exception {
        super(i);
        int n = 0; 
        inittID_number(s[n++]);
        inittFRS_NAME(s[n++]);
        inittE_CODE(s[n++]);
        inittFINANCIAL_YEAR(s[n++]);
        inittMONTH_NAME(s[n++]);
        inittWEEKDAY_WEEKEND(s[n++]);
        inittDAY_NIGHT(s[n++]);
        inittBUILDING_OR_PROPERTY_TYPE(s[n++]);
        inittLATE_CALL(s[n++]);
        inittMULTI_SEATED_FLAG(s[n++]);
        inittIGNITION_TO_DISCOVERY(s[n++]);
        inittDISCOVERY_TO_CALL(s[n++]);
        inittHOW_DISCOVERED_DESCRIPTION(s[n++]);
        inittFSO_APPLY(s[n++]);
        inittBUILDING_SAFETY_SYSTEM_COMPARTMENTATION_DESCRIPTION(s[n++]);
        inittBUILDING_SAFETY_SYSTEM_MEANS_OF_ESCAPE_DESCRIPTION(s[n++]);
        inittSAFETY_SYSTEM(s[n++]);
        inittBUILDING_OCCUPIED_AT_TIME_OF_INCIDENT(s[n++]);
        inittOCCUPIED_NORMAL(s[n++]);
        inittACCIDENTAL_OR_DELIBERATE(s[n++]);
        inittVEHICLES(s[n++]);
        inittVEHICLES_CODE(s[n++]);
        inittPERSONNEL(s[n++]);
        inittPERSONNEL_CODE(s[n++]);
        inittSTARTING_DELAY_DESCRIPTION(s[n++]);
        inittACTION_NON_FRS_DESCRIPTION(s[n++]);
        inittACTION_FRS_DESCRIPTION(s[n++]);
        inittCAUSE_OF_FIRE(s[n++]);
        inittIGNITION_POWER(s[n++]);
        inittSOURCE_OF_IGNITION(s[n++]);
        inittITEM_IGNITED(s[n++]);
        inittITEM_CAUSING_SPREAD(s[n++]);
        inittRAPID_FIRE_GROWTH(s[n++]);
        inittCAUSE_SUBSTANCES_DANGEROUS_DESCRIPTION(s[n++]);
        inittCAUSE_EXPLOSION_INVOLVED(s[n++]);
        inittCAUSE_SUBSTANCES_EXPLOSION_DESCRIPTION(s[n++]);
        inittCAUSE_EXPLOSION_STAGE_DESCRIPTION(s[n++]);
        inittCAUSE_EXPLOSION_CONTAINERS_DESCRIPTION(s[n++]);
        inittBUILDING_SPECIAL_CONSTRUCTION_DESCRIPTION(s[n++]);
        inittBUILDING_FLOORS_ABOVE_GROUND(s[n++]);
        inittBUILDING_FLOORS_BELOW_GROUND(s[n++]);
        inittBUILDING_FLOOR_ORIGIN(s[n++]);
        inittBUILDING_ORIGIN_FLOOR_SIZE_DESCRIPTION(s[n++]);
        inittBUILDING_ORIGIN_ROOM_SIZE_DESCRIPTION(s[n++]);
        inittFIRE_START_LOCATION(s[n++]);
        inittFIRE_SIZE_ON_ARRIVAL(s[n++]);
        inittOTHER_PROPERTY_AFFECTED_ON_ARRIVAL(s[n++]);
        inittBUILDING_FIRE_DAMAGE_AREA_DESCRIPTION(s[n++]);
        inittBUILDING_TOTAL_DAMAGE_AREA_DESCRIPTION(s[n++]);
        inittFIRE_SIZE_ON_ARRIVAL_DESCRIPTION(s[n++]);
        inittother_property_affected_close_d(s[n++]);
        inittspread_of_fire_d(s[n++]);
        inittRESPONSE_TIME(s[n++]);
        inittRESPONSE_TIME_CODE(s[n++]);
        inittTIME_AT_SCENE(s[n++]);
        inittTIME_AT_SCENE_CODE(s[n++]);
        inittFATALITY_CASUALTY(s[n++]);
        inittRESCUES(s[n++]);
        inittEVACUATIONS(s[n++]);
        inittEVACUATIONS_CODE(s[n++]);
        inittBUILDING_EVACUATION_DELAY_DESCRIPTION(s[n++]);
        inittBUILDING_EVACUATION_TIME_DESCRIPTION(s[n++]);
    }

    /**
     * @return A String representation of this.
     */
    @Override
    public String toString() {
        String r = toString0();
        r += ", FSO_APPLY=" + tFSO_APPLY;        
        r += toString1();
        r += ", SAFETY_SYSTEM=" + tSAFETY_SYSTEM;
        r += ", BUILDING_OCCUPIED_AT_TIME_OF_INCIDENT=" + tBUILDING_OCCUPIED_AT_TIME_OF_INCIDENT;
        r += ", OCCUPIED_NORMAL=" + tOCCUPIED_NORMAL;
        r += toString2();
        return r;
    }
    
    protected final void inittFSO_APPLY(String s) {
        if (!s.trim().isEmpty()) {
            tFSO_APPLY = s;
        } else {
            tFSO_APPLY = null;
        }
    }

    protected final void inittSAFETY_SYSTEM(String s) {
        if (!s.trim().isEmpty()) {
            tSAFETY_SYSTEM = s;
        } else {
            tSAFETY_SYSTEM = null;
        }
    }
}
