/*
 * Source code generated by uk.ac.leeds.ccg.data.fire.process.F_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.projects.fire.data.dwellings;

import uk.ac.leeds.ccg.projects.fire.id.F_RecordID;

public class F_Dwellings_Record1 extends F_Dwellings_Record0 {

    private static final long serialVersionUID = 1L;

    protected String tOCCUPANCY_TYPE;
    protected String tWERE_ACTIVE_SAFETY_SYSTEMS_PRESENT;
    protected String tALARM_SYSTEM;
    protected String tALARM_SYSTEM_TYPE;
    protected String tALARM_REASON_FOR_POOR_OUTCOME;

    public F_Dwellings_Record1(F_RecordID i, String[] s) throws Exception {
        super(i);
        inittID_number(s[0]);
        inittFRS_NAME(s[1]);
        inittE_CODE(s[2]);
        inittFINANCIAL_YEAR(s[3]);
        inittMONTH_NAME(s[4]);
        inittWEEKDAY_WEEKEND(s[5]);
        inittDAY_NIGHT(s[6]);
        inittBUILDING_OR_PROPERTY_TYPE(s[7]);
        inittLATE_CALL(s[8]);
        inittMULTI_SEATED_FLAG(s[9]);
        inittIGNITION_TO_DISCOVERY(s[10]);
        inittDISCOVERY_TO_CALL(s[11]);
        inittHOW_DISCOVERED_DESCRIPTION(s[12]);
        inittBUILDING_SAFETY_SYSTEM_COMPARTMENTATION_DESCRIPTION(s[13]);
        inittBUILDING_SAFETY_SYSTEM_MEANS_OF_ESCAPE_DESCRIPTION(s[14]);
        inittBUILDING_OCCUPIED_AT_TIME_OF_INCIDENT(s[15]);
        inittOCCUPANCY_TYPE(s[16]);
        inittOCCUPIED_NORMAL(s[17]);
        inittWERE_ACTIVE_SAFETY_SYSTEMS_PRESENT(s[18]);
        inittALARM_SYSTEM(s[19]);
        inittALARM_SYSTEM_TYPE(s[20]);
        inittALARM_REASON_FOR_POOR_OUTCOME(s[21]);
        inittACCIDENTAL_OR_DELIBERATE(s[22]);
        inittVEHICLES(s[23]);
        inittVEHICLES_CODE(s[24]);
        inittPERSONNEL(s[25]);
        inittPERSONNEL_CODE(s[26]);
        inittSTARTING_DELAY_DESCRIPTION(s[27]);
        inittACTION_NON_FRS_DESCRIPTION(s[28]);
        inittACTION_FRS_DESCRIPTION(s[29]);
        inittCAUSE_OF_FIRE(s[30]);
        inittIGNITION_POWER(s[31]);
        inittSOURCE_OF_IGNITION(s[32]);
        inittITEM_IGNITED(s[33]);
        inittITEM_CAUSING_SPREAD(s[34]);
        inittRAPID_FIRE_GROWTH(s[35]);
        inittCAUSE_SUBSTANCES_DANGEROUS_DESCRIPTION(s[36]);
        inittCAUSE_EXPLOSION_INVOLVED(s[37]);
        inittCAUSE_SUBSTANCES_EXPLOSION_DESCRIPTION(s[38]);
        inittCAUSE_EXPLOSION_STAGE_DESCRIPTION(s[39]);
        inittCAUSE_EXPLOSION_CONTAINERS_DESCRIPTION(s[40]);
        inittBUILDING_SPECIAL_CONSTRUCTION_DESCRIPTION(s[41]);
        inittBUILDING_FLOORS_ABOVE_GROUND(s[42]);
        inittBUILDING_FLOORS_BELOW_GROUND(s[43]);
        inittBUILDING_FLOOR_ORIGIN(s[44]);
        inittBUILDING_ORIGIN_FLOOR_SIZE_DESCRIPTION(s[45]);
        inittBUILDING_ORIGIN_ROOM_SIZE_DESCRIPTION(s[46]);
        inittFIRE_START_LOCATION(s[47]);
        inittFIRE_SIZE_ON_ARRIVAL(s[48]);
        inittOTHER_PROPERTY_AFFECTED_ON_ARRIVAL(s[49]);
        inittBUILDING_FIRE_DAMAGE_AREA_DESCRIPTION(s[50]);
        inittBUILDING_TOTAL_DAMAGE_AREA_DESCRIPTION(s[51]);
        inittFIRE_SIZE_ON_ARRIVAL_DESCRIPTION(s[52]);
        inittother_property_affected_close_d(s[53]);
        inittspread_of_fire_d(s[54]);
        inittRESPONSE_TIME(s[55]);
        inittRESPONSE_TIME_CODE(s[56]);
        inittTIME_AT_SCENE(s[57]);
        inittTIME_AT_SCENE_CODE(s[58]);
        inittFATALITY_CASUALTY(s[59]);
        inittRESCUES(s[60]);
        inittEVACUATIONS(s[61]);
        inittEVACUATIONS_CODE(s[62]);
        inittBUILDING_EVACUATION_DELAY_DESCRIPTION(s[63]);
        inittBUILDING_EVACUATION_TIME_DESCRIPTION(s[64]);
    }

    /**
     * @return A String representation of this.
     */
    @Override
    public String toString() {
        String r = toString0();
        r += toString1();
        r += ", BUILDING_OCCUPIED_AT_TIME_OF_INCIDENT=" + tBUILDING_OCCUPIED_AT_TIME_OF_INCIDENT;
        r += ", OCCUPANCY_TYPE=" + tOCCUPANCY_TYPE;
        r += ", OCCUPIED_NORMAL=" + tOCCUPIED_NORMAL;
        r += ", WERE_ACTIVE_SAFETY_SYSTEMS_PRESENT=" + tWERE_ACTIVE_SAFETY_SYSTEMS_PRESENT;
        r += ", ALARM_SYSTEM=" + tALARM_SYSTEM;
        r += ", ALARM_SYSTEM_TYPE=" + tALARM_SYSTEM_TYPE;
        r += ", ALARM_REASON_FOR_POOR_OUTCOME=" + tALARM_REASON_FOR_POOR_OUTCOME;
        r += toString2();
        return r;
    }
    
    protected final void inittOCCUPANCY_TYPE(String s) {
        if (!s.trim().isEmpty()) {
            tOCCUPANCY_TYPE = s;
        } else {
            tOCCUPANCY_TYPE = null;
        }
    }

    protected final void inittWERE_ACTIVE_SAFETY_SYSTEMS_PRESENT(String s) {
        if (!s.trim().isEmpty()) {
            tWERE_ACTIVE_SAFETY_SYSTEMS_PRESENT = s;
        } else {
            tWERE_ACTIVE_SAFETY_SYSTEMS_PRESENT = null;
        }
    }

    protected final void inittALARM_SYSTEM(String s) {
        if (!s.trim().isEmpty()) {
            tALARM_SYSTEM = s;
        } else {
            tALARM_SYSTEM = null;
        }
    }

    protected final void inittALARM_SYSTEM_TYPE(String s) {
        if (!s.trim().isEmpty()) {
            tALARM_SYSTEM_TYPE = s;
        } else {
            tALARM_SYSTEM_TYPE = null;
        }
    }

    protected final void inittALARM_REASON_FOR_POOR_OUTCOME(String s) {
        if (!s.trim().isEmpty()) {
            tALARM_REASON_FOR_POOR_OUTCOME = s;
        } else {
            tALARM_REASON_FOR_POOR_OUTCOME = null;
        }
    }

    public final String gettOCCUPANCY_TYPE() {
        return tOCCUPANCY_TYPE;
    }

    public final String gettWERE_ACTIVE_SAFETY_SYSTEMS_PRESENT() {
        return tWERE_ACTIVE_SAFETY_SYSTEMS_PRESENT;
    }

    public final String gettALARM_SYSTEM() {
        return tALARM_SYSTEM;
    }

    public final String gettALARM_SYSTEM_TYPE() {
        return tALARM_SYSTEM_TYPE;
    }

    public final String gettALARM_REASON_FOR_POOR_OUTCOME() {
        return tALARM_REASON_FOR_POOR_OUTCOME;
    }
}
